Repository AY2425S1-CS2103T-W13-3/tp, pull requests merged in 2024-11, with the labels that each got.

#189 Update Delete and clear to include confirm
  docs/UserGuide.md
Labels: severity.VeryLow

#183 Enhance UI for detailed log view
  src/main/java/seedu/address/logic/commands/ListLogsCommand.java
  src/main/java/seedu/address/model/log/Log.java
  src/main/java/seedu/address/ui/SessionLogCard.java
  src/main/java/seedu/address/ui/SessionLogDetail.java
  src/main/java/seedu/address/ui/SessionLogPanel.java
  src/main/resources/view/SessionLogCard.fxml
  src/main/resources/view/SessionLogDetail.fxml
Labels: type.Enhancement, alpha-bug

#191 Fix feedback window bug for invalid delete
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: severity.Low, alpha-bug

#217 Add additional status with Ui improvements
  src/main/java/seedu/address/model/person/Status.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement

#231 Include a new status & throw error for missing status input
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Status.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: alpha-bug

#261 Update user guide images
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/logsAlexResult.png
Labels: UG-edits

#266 Add colour tagging for new patients and update Ui UML
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
Labels: type.Enhancement

#267 Refactor tags to statuses in UG
  docs/UserGuide.md
Labels: UG-edits

#270 Miscellaneous updates + UG update
  docs/UserGuide.md
  docs/img.png
  docs/img_1.png
  src/main/java/seedu/address/logic/commands/AddLogEntryCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
Labels: type.Enhancement

#277 Update dg user stories
  docs/DeveloperGuide.md
Labels: DG-edits

#283 Update use cases in DG
  docs/DeveloperGuide.md
Labels: DG-edits

#364 Update UG and DeleteCommand message usage string
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: type.Bug, UG-edits

#362 Fix invalid date bug
  src/main/java/seedu/address/logic/parser/AddLogCommandParser.java
  src/main/java/seedu/address/logic/parser/AddLogEntryCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/log/AppointmentDate.java
Labels: type.Bug

#373 Update DG
  docs/DeveloperGuide.md
Labels: DG-edits

#361 Fix CommandResult equals and fix test cases
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/model/log/LogEntry.java
  src/main/java/seedu/address/ui/AddLogPopup.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
Labels: alpha-bug
